apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.nameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: "k8s.homework.user-service"
    http:
      paths:
      - path: /epamapp/stanislav_menko(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-app-service
            port:
              number: 80
  - host: "k8s.homework.post-service"
    http:
      paths:
      - path: /epamapp/stanislav_menko(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: post-app-service
            port:
              number: 80